spring:
  application:
    name: hello-admin-service
  profiles:
    active:
      - security
      - cache
      - datasource

server:
  port: 9000
  servlet:
    context-path: /hello-admin
    encoding:
      force: true

logging:
  level:
    org:
      springframework: warn
      apache: warn
      reflections: warn
